# Generated by Django 5.1.1 on 2024-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_enabled',
            new_name='is_enable',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_enabled',
            new_name='is_enable',
        ),
    ]
